
package mx.movistar.col.lead.business.ws.amplifica.model;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;




/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wundermanEnd", targetNamespace = "http://198.100.158.107/wunderman/", 
wsdlLocation = "WSDL/amplifica.wsdl")
public class WundermanEnd
    extends Service
{

    private final static URL WUNDERMANEND_WSDL_LOCATION;
    private final static WebServiceException WUNDERMANEND_EXCEPTION;
    private final static QName WUNDERMANEND_QNAME = new QName("http://198.100.158.107/wunderman/", "wundermanEnd");
    
    
    static {
        URL url = null;
        WebServiceException e = null;
        try {        	
        	        	
        	url = WundermanEnd.class.getClassLoader().getResource("WSDL/amplifica.wsdl");
        }catch(Exception ex) {        	  
        	  e = new WebServiceException(ex);
        }
        WUNDERMANEND_WSDL_LOCATION = url;
        WUNDERMANEND_EXCEPTION = e;
    }

    public WundermanEnd() {
        super(__getWsdlLocation(), WUNDERMANEND_QNAME);
    }

    public WundermanEnd(WebServiceFeature... features) {
        super(__getWsdlLocation(), WUNDERMANEND_QNAME, features);
    }

    public WundermanEnd(URL wsdlLocation) {
        super(wsdlLocation, WUNDERMANEND_QNAME);
    }

    public WundermanEnd(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WUNDERMANEND_QNAME, features);
    }

    public WundermanEnd(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WundermanEnd(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WundermanEndSoap
     */
    @WebEndpoint(name = "wundermanEndSoap")
    public WundermanEndSoap getWundermanEndSoap() {
        return super.getPort(new QName("http://198.100.158.107/wunderman/", "wundermanEndSoap"), WundermanEndSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WundermanEndSoap
     */
    @WebEndpoint(name = "wundermanEndSoap")
    public WundermanEndSoap getWundermanEndSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://198.100.158.107/wunderman/", "wundermanEndSoap"), WundermanEndSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WUNDERMANEND_EXCEPTION!= null) {
            throw WUNDERMANEND_EXCEPTION;
        }
        return WUNDERMANEND_WSDL_LOCATION;
    }

}
