
package mx.movistar.col.lead.business.ws.amplifica.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wundermanEndSoap", targetNamespace = "http://198.100.158.107/wunderman/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WundermanEndSoap {


    /**http://198.100.158.107/wunderman/index.php
     * sendLead($lead, $rdph, $natural)
     *                 
     *                 Parametros de entrada:
     *                 
     *                 lead::Obj => lead data
     *                 rdph::int => reject duplicate phone for hours (default 6 hour)
     *                 natural::int => tipo de lead, 1 organico 0 otros (default 0)
     *                 
     *                 CODIGOS DE RETORNO
     *                 
     *                 200 OPERACION REALIZADA EXITO MAS ID
     *                 400 ERROR EN DATOS   DESCRIPCION
     *                 500 ERROR INTERNO DEL SERVIDOR
     * 
     * @param natural
     * @param lead
     * @param rdph
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://198.100.158.107/wunderman/sendLead")
    @WebResult(partName = "return")
    public String sendLead(
        @WebParam(name = "lead", partName = "lead")
        Lead lead,
        @WebParam(name = "rdph", partName = "rdph")
        int rdph,
        @WebParam(name = "natural", partName = "natural")
        int natural);

}
