/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mx.movistar.col.lead.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the CallCenter service. Represents a row in the &quot;LEAD_CallCenter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>mx.movistar.col.lead.model.impl.CallCenterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>mx.movistar.col.lead.model.impl.CallCenterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CallCenter
 * @generated
 */
@ProviderType
public interface CallCenterModel
	extends BaseModel<CallCenter>, GroupedModel, LocalizedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a call center model instance should use the {@link CallCenter} interface instead.
	 */

	/**
	 * Returns the primary key of this call center.
	 *
	 * @return the primary key of this call center
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this call center.
	 *
	 * @param primaryKey the primary key of this call center
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this call center.
	 *
	 * @return the uuid of this call center
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this call center.
	 *
	 * @param uuid the uuid of this call center
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the call center ID of this call center.
	 *
	 * @return the call center ID of this call center
	 */
	public long getCallCenterId();

	/**
	 * Sets the call center ID of this call center.
	 *
	 * @param callCenterId the call center ID of this call center
	 */
	public void setCallCenterId(long callCenterId);

	/**
	 * Returns the campaign ID of this call center.
	 *
	 * @return the campaign ID of this call center
	 */
	public long getCampaignId();

	/**
	 * Sets the campaign ID of this call center.
	 *
	 * @param campaignId the campaign ID of this call center
	 */
	public void setCampaignId(long campaignId);

	/**
	 * Returns the group ID of this call center.
	 *
	 * @return the group ID of this call center
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this call center.
	 *
	 * @param groupId the group ID of this call center
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this call center.
	 *
	 * @return the company ID of this call center
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this call center.
	 *
	 * @param companyId the company ID of this call center
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this call center.
	 *
	 * @return the user ID of this call center
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this call center.
	 *
	 * @param userId the user ID of this call center
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this call center.
	 *
	 * @return the user uuid of this call center
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this call center.
	 *
	 * @param userUuid the user uuid of this call center
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this call center.
	 *
	 * @return the user name of this call center
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this call center.
	 *
	 * @param userName the user name of this call center
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this call center.
	 *
	 * @return the create date of this call center
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this call center.
	 *
	 * @param createDate the create date of this call center
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this call center.
	 *
	 * @return the modified date of this call center
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this call center.
	 *
	 * @param modifiedDate the modified date of this call center
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the due date of this call center.
	 *
	 * @return the due date of this call center
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this call center.
	 *
	 * @param dueDate the due date of this call center
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the status of this call center.
	 *
	 * @return the status of this call center
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this call center.
	 *
	 * @param status the status of this call center
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this call center.
	 *
	 * @return the status by user ID of this call center
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this call center.
	 *
	 * @param statusByUserId the status by user ID of this call center
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this call center.
	 *
	 * @return the status by user uuid of this call center
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this call center.
	 *
	 * @param statusByUserUuid the status by user uuid of this call center
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this call center.
	 *
	 * @return the status by user name of this call center
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this call center.
	 *
	 * @param statusByUserName the status by user name of this call center
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this call center.
	 *
	 * @return the status date of this call center
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this call center.
	 *
	 * @param statusDate the status date of this call center
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the title of this call center.
	 *
	 * @return the title of this call center
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this call center in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this call center
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this call center in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this call center. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this call center in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this call center
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this call center in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this call center
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this call center.
	 *
	 * @return the locales and localized titles of this call center
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this call center.
	 *
	 * @param title the title of this call center
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this call center in the language.
	 *
	 * @param title the localized title of this call center
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this call center in the language, and sets the default locale.
	 *
	 * @param title the localized title of this call center
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this call center from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this call center
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this call center from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this call center
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the description of this call center.
	 *
	 * @return the description of this call center
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this call center.
	 *
	 * @param description the description of this call center
	 */
	public void setDescription(String description);

	/**
	 * Returns the source of this call center.
	 *
	 * @return the source of this call center
	 */
	@AutoEscape
	public String getSource();

	/**
	 * Sets the source of this call center.
	 *
	 * @param source the source of this call center
	 */
	public void setSource(String source);

	/**
	 * Returns the type of this call center.
	 *
	 * @return the type of this call center
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this call center.
	 *
	 * @param type the type of this call center
	 */
	public void setType(String type);

	/**
	 * Returns the product of this call center.
	 *
	 * @return the product of this call center
	 */
	@AutoEscape
	public String getProduct();

	/**
	 * Sets the product of this call center.
	 *
	 * @param product the product of this call center
	 */
	public void setProduct(String product);

	/**
	 * Returns the has email of this call center.
	 *
	 * @return the has email of this call center
	 */
	public boolean getHasEmail();

	/**
	 * Returns <code>true</code> if this call center is has email.
	 *
	 * @return <code>true</code> if this call center is has email; <code>false</code> otherwise
	 */
	public boolean isHasEmail();

	/**
	 * Sets whether this call center is has email.
	 *
	 * @param hasEmail the has email of this call center
	 */
	public void setHasEmail(boolean hasEmail);

	/**
	 * Returns the has phone of this call center.
	 *
	 * @return the has phone of this call center
	 */
	public boolean getHasPhone();

	/**
	 * Returns <code>true</code> if this call center is has phone.
	 *
	 * @return <code>true</code> if this call center is has phone; <code>false</code> otherwise
	 */
	public boolean isHasPhone();

	/**
	 * Sets whether this call center is has phone.
	 *
	 * @param hasPhone the has phone of this call center
	 */
	public void setHasPhone(boolean hasPhone);

	/**
	 * Returns the has name of this call center.
	 *
	 * @return the has name of this call center
	 */
	public boolean getHasName();

	/**
	 * Returns <code>true</code> if this call center is has name.
	 *
	 * @return <code>true</code> if this call center is has name; <code>false</code> otherwise
	 */
	public boolean isHasName();

	/**
	 * Sets whether this call center is has name.
	 *
	 * @param hasName the has name of this call center
	 */
	public void setHasName(boolean hasName);

	/**
	 * Returns the extra1 of this call center.
	 *
	 * @return the extra1 of this call center
	 */
	public boolean getExtra1();

	/**
	 * Returns <code>true</code> if this call center is extra1.
	 *
	 * @return <code>true</code> if this call center is extra1; <code>false</code> otherwise
	 */
	public boolean isExtra1();

	/**
	 * Sets whether this call center is extra1.
	 *
	 * @param extra1 the extra1 of this call center
	 */
	public void setExtra1(boolean extra1);

	/**
	 * Returns the extra2 of this call center.
	 *
	 * @return the extra2 of this call center
	 */
	public boolean getExtra2();

	/**
	 * Returns <code>true</code> if this call center is extra2.
	 *
	 * @return <code>true</code> if this call center is extra2; <code>false</code> otherwise
	 */
	public boolean isExtra2();

	/**
	 * Sets whether this call center is extra2.
	 *
	 * @param extra2 the extra2 of this call center
	 */
	public void setExtra2(boolean extra2);

	/**
	 * Returns the extra3 of this call center.
	 *
	 * @return the extra3 of this call center
	 */
	public boolean getExtra3();

	/**
	 * Returns <code>true</code> if this call center is extra3.
	 *
	 * @return <code>true</code> if this call center is extra3; <code>false</code> otherwise
	 */
	public boolean isExtra3();

	/**
	 * Sets whether this call center is extra3.
	 *
	 * @param extra3 the extra3 of this call center
	 */
	public void setExtra3(boolean extra3);

	/**
	 * Returns the total scoring of this call center.
	 *
	 * @return the total scoring of this call center
	 */
	public int getTotalScoring();

	/**
	 * Sets the total scoring of this call center.
	 *
	 * @param totalScoring the total scoring of this call center
	 */
	public void setTotalScoring(int totalScoring);

	/**
	 * Returns <code>true</code> if this call center is approved.
	 *
	 * @return <code>true</code> if this call center is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this call center is denied.
	 *
	 * @return <code>true</code> if this call center is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this call center is a draft.
	 *
	 * @return <code>true</code> if this call center is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this call center is expired.
	 *
	 * @return <code>true</code> if this call center is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this call center is inactive.
	 *
	 * @return <code>true</code> if this call center is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this call center is incomplete.
	 *
	 * @return <code>true</code> if this call center is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this call center is pending.
	 *
	 * @return <code>true</code> if this call center is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this call center is scheduled.
	 *
	 * @return <code>true</code> if this call center is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(mx.movistar.col.lead.model.CallCenter callCenter);

	@Override
	public int hashCode();

	@Override
	public CacheModel<mx.movistar.col.lead.model.CallCenter> toCacheModel();

	@Override
	public mx.movistar.col.lead.model.CallCenter toEscapedModel();

	@Override
	public mx.movistar.col.lead.model.CallCenter toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}