/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mx.movistar.col.lead.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LeadScoring service. Represents a row in the &quot;LEAD_LeadScoring&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>mx.movistar.col.lead.model.impl.LeadScoringModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>mx.movistar.col.lead.model.impl.LeadScoringImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeadScoring
 * @generated
 */
@ProviderType
public interface LeadScoringModel extends BaseModel<LeadScoring> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lead scoring model instance should use the {@link LeadScoring} interface instead.
	 */

	/**
	 * Returns the primary key of this lead scoring.
	 *
	 * @return the primary key of this lead scoring
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lead scoring.
	 *
	 * @param primaryKey the primary key of this lead scoring
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lead scoring ID of this lead scoring.
	 *
	 * @return the lead scoring ID of this lead scoring
	 */
	public long getLeadScoringId();

	/**
	 * Sets the lead scoring ID of this lead scoring.
	 *
	 * @param leadScoringId the lead scoring ID of this lead scoring
	 */
	public void setLeadScoringId(long leadScoringId);

	/**
	 * Returns the group ID of this lead scoring.
	 *
	 * @return the group ID of this lead scoring
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this lead scoring.
	 *
	 * @param groupId the group ID of this lead scoring
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the lead ID of this lead scoring.
	 *
	 * @return the lead ID of this lead scoring
	 */
	public long getLeadId();

	/**
	 * Sets the lead ID of this lead scoring.
	 *
	 * @param leadId the lead ID of this lead scoring
	 */
	public void setLeadId(long leadId);

	/**
	 * Returns the create date of this lead scoring.
	 *
	 * @return the create date of this lead scoring
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this lead scoring.
	 *
	 * @param createDate the create date of this lead scoring
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the msisdn of this lead scoring.
	 *
	 * @return the msisdn of this lead scoring
	 */
	@AutoEscape
	public String getMsisdn();

	/**
	 * Sets the msisdn of this lead scoring.
	 *
	 * @param msisdn the msisdn of this lead scoring
	 */
	public void setMsisdn(String msisdn);

	/**
	 * Returns the email of this lead scoring.
	 *
	 * @return the email of this lead scoring
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this lead scoring.
	 *
	 * @param email the email of this lead scoring
	 */
	public void setEmail(String email);

	/**
	 * Returns the name of this lead scoring.
	 *
	 * @return the name of this lead scoring
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this lead scoring.
	 *
	 * @param name the name of this lead scoring
	 */
	public void setName(String name);

	/**
	 * Returns the surname of this lead scoring.
	 *
	 * @return the surname of this lead scoring
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this lead scoring.
	 *
	 * @param surname the surname of this lead scoring
	 */
	public void setSurname(String surname);

	/**
	 * Returns the extra1 of this lead scoring.
	 *
	 * @return the extra1 of this lead scoring
	 */
	@AutoEscape
	public String getExtra1();

	/**
	 * Sets the extra1 of this lead scoring.
	 *
	 * @param extra1 the extra1 of this lead scoring
	 */
	public void setExtra1(String extra1);

	/**
	 * Returns the extra2 of this lead scoring.
	 *
	 * @return the extra2 of this lead scoring
	 */
	@AutoEscape
	public String getExtra2();

	/**
	 * Sets the extra2 of this lead scoring.
	 *
	 * @param extra2 the extra2 of this lead scoring
	 */
	public void setExtra2(String extra2);

	/**
	 * Returns the extra3 of this lead scoring.
	 *
	 * @return the extra3 of this lead scoring
	 */
	@AutoEscape
	public String getExtra3();

	/**
	 * Sets the extra3 of this lead scoring.
	 *
	 * @param extra3 the extra3 of this lead scoring
	 */
	public void setExtra3(String extra3);

	/**
	 * Returns the date schedule of this lead scoring.
	 *
	 * @return the date schedule of this lead scoring
	 */
	public Date getDateSchedule();

	/**
	 * Sets the date schedule of this lead scoring.
	 *
	 * @param dateSchedule the date schedule of this lead scoring
	 */
	public void setDateSchedule(Date dateSchedule);

	/**
	 * Returns the url of this lead scoring.
	 *
	 * @return the url of this lead scoring
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this lead scoring.
	 *
	 * @param url the url of this lead scoring
	 */
	public void setUrl(String url);

	/**
	 * Returns the utm source of this lead scoring.
	 *
	 * @return the utm source of this lead scoring
	 */
	@AutoEscape
	public String getUtmSource();

	/**
	 * Sets the utm source of this lead scoring.
	 *
	 * @param utmSource the utm source of this lead scoring
	 */
	public void setUtmSource(String utmSource);

	/**
	 * Returns the utm medium of this lead scoring.
	 *
	 * @return the utm medium of this lead scoring
	 */
	@AutoEscape
	public String getUtmMedium();

	/**
	 * Sets the utm medium of this lead scoring.
	 *
	 * @param utmMedium the utm medium of this lead scoring
	 */
	public void setUtmMedium(String utmMedium);

	/**
	 * Returns the utm content of this lead scoring.
	 *
	 * @return the utm content of this lead scoring
	 */
	@AutoEscape
	public String getUtmContent();

	/**
	 * Sets the utm content of this lead scoring.
	 *
	 * @param utmContent the utm content of this lead scoring
	 */
	public void setUtmContent(String utmContent);

	/**
	 * Returns the utm campaign of this lead scoring.
	 *
	 * @return the utm campaign of this lead scoring
	 */
	@AutoEscape
	public String getUtmCampaign();

	/**
	 * Sets the utm campaign of this lead scoring.
	 *
	 * @param utmCampaign the utm campaign of this lead scoring
	 */
	public void setUtmCampaign(String utmCampaign);

	/**
	 * Returns the utm term of this lead scoring.
	 *
	 * @return the utm term of this lead scoring
	 */
	@AutoEscape
	public String getUtmTerm();

	/**
	 * Sets the utm term of this lead scoring.
	 *
	 * @param utmTerm the utm term of this lead scoring
	 */
	public void setUtmTerm(String utmTerm);

	/**
	 * Returns the other source of this lead scoring.
	 *
	 * @return the other source of this lead scoring
	 */
	@AutoEscape
	public String getOtherSource();

	/**
	 * Sets the other source of this lead scoring.
	 *
	 * @param otherSource the other source of this lead scoring
	 */
	public void setOtherSource(String otherSource);

	/**
	 * Returns the response ws of this lead scoring.
	 *
	 * @return the response ws of this lead scoring
	 */
	@AutoEscape
	public String getResponseWS();

	/**
	 * Sets the response ws of this lead scoring.
	 *
	 * @param responseWS the response ws of this lead scoring
	 */
	public void setResponseWS(String responseWS);

	/**
	 * Returns the id ccws of this lead scoring.
	 *
	 * @return the id ccws of this lead scoring
	 */
	@AutoEscape
	public String getIdCCWS();

	/**
	 * Sets the id ccws of this lead scoring.
	 *
	 * @param idCCWS the id ccws of this lead scoring
	 */
	public void setIdCCWS(String idCCWS);

	/**
	 * Returns the re try date of this lead scoring.
	 *
	 * @return the re try date of this lead scoring
	 */
	public Date getReTryDate();

	/**
	 * Sets the re try date of this lead scoring.
	 *
	 * @param reTryDate the re try date of this lead scoring
	 */
	public void setReTryDate(Date reTryDate);

	/**
	 * Returns the ip cliente of this lead scoring.
	 *
	 * @return the ip cliente of this lead scoring
	 */
	@AutoEscape
	public String getIpCliente();

	/**
	 * Sets the ip cliente of this lead scoring.
	 *
	 * @param ipCliente the ip cliente of this lead scoring
	 */
	public void setIpCliente(String ipCliente);

	/**
	 * Returns the origen of this lead scoring.
	 *
	 * @return the origen of this lead scoring
	 */
	@AutoEscape
	public String getOrigen();

	/**
	 * Sets the origen of this lead scoring.
	 *
	 * @param origen the origen of this lead scoring
	 */
	public void setOrigen(String origen);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(mx.movistar.col.lead.model.LeadScoring leadScoring);

	@Override
	public int hashCode();

	@Override
	public CacheModel<mx.movistar.col.lead.model.LeadScoring> toCacheModel();

	@Override
	public mx.movistar.col.lead.model.LeadScoring toEscapedModel();

	@Override
	public mx.movistar.col.lead.model.LeadScoring toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}