/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mx.movistar.col.lead.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import mx.movistar.col.lead.service.persistence.NirPK;

/**
 * The base model interface for the Nir service. Represents a row in the &quot;LEAD_Nir&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>mx.movistar.col.lead.model.impl.NirModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>mx.movistar.col.lead.model.impl.NirImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Nir
 * @generated
 */
@ProviderType
public interface NirModel extends BaseModel<Nir> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a nir model instance should use the {@link Nir} interface instead.
	 */

	/**
	 * Returns the primary key of this nir.
	 *
	 * @return the primary key of this nir
	 */
	public NirPK getPrimaryKey();

	/**
	 * Sets the primary key of this nir.
	 *
	 * @param primaryKey the primary key of this nir
	 */
	public void setPrimaryKey(NirPK primaryKey);

	/**
	 * Returns the lada of this nir.
	 *
	 * @return the lada of this nir
	 */
	@AutoEscape
	public String getLada();

	/**
	 * Sets the lada of this nir.
	 *
	 * @param lada the lada of this nir
	 */
	public void setLada(String lada);

	/**
	 * Returns the serie of this nir.
	 *
	 * @return the serie of this nir
	 */
	@AutoEscape
	public String getSerie();

	/**
	 * Sets the serie of this nir.
	 *
	 * @param serie the serie of this nir
	 */
	public void setSerie(String serie);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(mx.movistar.col.lead.model.Nir nir);

	@Override
	public int hashCode();

	@Override
	public CacheModel<mx.movistar.col.lead.model.Nir> toCacheModel();

	@Override
	public mx.movistar.col.lead.model.Nir toEscapedModel();

	@Override
	public mx.movistar.col.lead.model.Nir toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}