/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mx.movistar.col.lead.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

import mx.movistar.col.lead.model.Nir;
import mx.movistar.col.lead.service.NirService;
import mx.movistar.col.lead.service.persistence.BlackListPersistence;
import mx.movistar.col.lead.service.persistence.CallCenterFinder;
import mx.movistar.col.lead.service.persistence.CallCenterPersistence;
import mx.movistar.col.lead.service.persistence.CampaignPersistence;
import mx.movistar.col.lead.service.persistence.LeadFinder;
import mx.movistar.col.lead.service.persistence.LeadPersistence;
import mx.movistar.col.lead.service.persistence.LeadScoringPersistence;
import mx.movistar.col.lead.service.persistence.NirPersistence;

/**
 * Provides the base implementation for the nir remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link mx.movistar.col.lead.service.impl.NirServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see mx.movistar.col.lead.service.impl.NirServiceImpl
 * @generated
 */
public abstract class NirServiceBaseImpl
	extends BaseServiceImpl implements NirService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>NirService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>mx.movistar.col.lead.service.NirServiceUtil</code>.
	 */

	/**
	 * Returns the black list local service.
	 *
	 * @return the black list local service
	 */
	public mx.movistar.col.lead.service.BlackListLocalService
		getBlackListLocalService() {

		return blackListLocalService;
	}

	/**
	 * Sets the black list local service.
	 *
	 * @param blackListLocalService the black list local service
	 */
	public void setBlackListLocalService(
		mx.movistar.col.lead.service.BlackListLocalService
			blackListLocalService) {

		this.blackListLocalService = blackListLocalService;
	}

	/**
	 * Returns the black list remote service.
	 *
	 * @return the black list remote service
	 */
	public mx.movistar.col.lead.service.BlackListService getBlackListService() {
		return blackListService;
	}

	/**
	 * Sets the black list remote service.
	 *
	 * @param blackListService the black list remote service
	 */
	public void setBlackListService(
		mx.movistar.col.lead.service.BlackListService blackListService) {

		this.blackListService = blackListService;
	}

	/**
	 * Returns the black list persistence.
	 *
	 * @return the black list persistence
	 */
	public BlackListPersistence getBlackListPersistence() {
		return blackListPersistence;
	}

	/**
	 * Sets the black list persistence.
	 *
	 * @param blackListPersistence the black list persistence
	 */
	public void setBlackListPersistence(
		BlackListPersistence blackListPersistence) {

		this.blackListPersistence = blackListPersistence;
	}

	/**
	 * Returns the call center local service.
	 *
	 * @return the call center local service
	 */
	public mx.movistar.col.lead.service.CallCenterLocalService
		getCallCenterLocalService() {

		return callCenterLocalService;
	}

	/**
	 * Sets the call center local service.
	 *
	 * @param callCenterLocalService the call center local service
	 */
	public void setCallCenterLocalService(
		mx.movistar.col.lead.service.CallCenterLocalService
			callCenterLocalService) {

		this.callCenterLocalService = callCenterLocalService;
	}

	/**
	 * Returns the call center remote service.
	 *
	 * @return the call center remote service
	 */
	public mx.movistar.col.lead.service.CallCenterService
		getCallCenterService() {

		return callCenterService;
	}

	/**
	 * Sets the call center remote service.
	 *
	 * @param callCenterService the call center remote service
	 */
	public void setCallCenterService(
		mx.movistar.col.lead.service.CallCenterService callCenterService) {

		this.callCenterService = callCenterService;
	}

	/**
	 * Returns the call center persistence.
	 *
	 * @return the call center persistence
	 */
	public CallCenterPersistence getCallCenterPersistence() {
		return callCenterPersistence;
	}

	/**
	 * Sets the call center persistence.
	 *
	 * @param callCenterPersistence the call center persistence
	 */
	public void setCallCenterPersistence(
		CallCenterPersistence callCenterPersistence) {

		this.callCenterPersistence = callCenterPersistence;
	}

	/**
	 * Returns the call center finder.
	 *
	 * @return the call center finder
	 */
	public CallCenterFinder getCallCenterFinder() {
		return callCenterFinder;
	}

	/**
	 * Sets the call center finder.
	 *
	 * @param callCenterFinder the call center finder
	 */
	public void setCallCenterFinder(CallCenterFinder callCenterFinder) {
		this.callCenterFinder = callCenterFinder;
	}

	/**
	 * Returns the campaign local service.
	 *
	 * @return the campaign local service
	 */
	public mx.movistar.col.lead.service.CampaignLocalService
		getCampaignLocalService() {

		return campaignLocalService;
	}

	/**
	 * Sets the campaign local service.
	 *
	 * @param campaignLocalService the campaign local service
	 */
	public void setCampaignLocalService(
		mx.movistar.col.lead.service.CampaignLocalService
			campaignLocalService) {

		this.campaignLocalService = campaignLocalService;
	}

	/**
	 * Returns the campaign remote service.
	 *
	 * @return the campaign remote service
	 */
	public mx.movistar.col.lead.service.CampaignService getCampaignService() {
		return campaignService;
	}

	/**
	 * Sets the campaign remote service.
	 *
	 * @param campaignService the campaign remote service
	 */
	public void setCampaignService(
		mx.movistar.col.lead.service.CampaignService campaignService) {

		this.campaignService = campaignService;
	}

	/**
	 * Returns the campaign persistence.
	 *
	 * @return the campaign persistence
	 */
	public CampaignPersistence getCampaignPersistence() {
		return campaignPersistence;
	}

	/**
	 * Sets the campaign persistence.
	 *
	 * @param campaignPersistence the campaign persistence
	 */
	public void setCampaignPersistence(
		CampaignPersistence campaignPersistence) {

		this.campaignPersistence = campaignPersistence;
	}

	/**
	 * Returns the lead local service.
	 *
	 * @return the lead local service
	 */
	public mx.movistar.col.lead.service.LeadLocalService getLeadLocalService() {
		return leadLocalService;
	}

	/**
	 * Sets the lead local service.
	 *
	 * @param leadLocalService the lead local service
	 */
	public void setLeadLocalService(
		mx.movistar.col.lead.service.LeadLocalService leadLocalService) {

		this.leadLocalService = leadLocalService;
	}

	/**
	 * Returns the lead remote service.
	 *
	 * @return the lead remote service
	 */
	public mx.movistar.col.lead.service.LeadService getLeadService() {
		return leadService;
	}

	/**
	 * Sets the lead remote service.
	 *
	 * @param leadService the lead remote service
	 */
	public void setLeadService(
		mx.movistar.col.lead.service.LeadService leadService) {

		this.leadService = leadService;
	}

	/**
	 * Returns the lead persistence.
	 *
	 * @return the lead persistence
	 */
	public LeadPersistence getLeadPersistence() {
		return leadPersistence;
	}

	/**
	 * Sets the lead persistence.
	 *
	 * @param leadPersistence the lead persistence
	 */
	public void setLeadPersistence(LeadPersistence leadPersistence) {
		this.leadPersistence = leadPersistence;
	}

	/**
	 * Returns the lead finder.
	 *
	 * @return the lead finder
	 */
	public LeadFinder getLeadFinder() {
		return leadFinder;
	}

	/**
	 * Sets the lead finder.
	 *
	 * @param leadFinder the lead finder
	 */
	public void setLeadFinder(LeadFinder leadFinder) {
		this.leadFinder = leadFinder;
	}

	/**
	 * Returns the lead scoring local service.
	 *
	 * @return the lead scoring local service
	 */
	public mx.movistar.col.lead.service.LeadScoringLocalService
		getLeadScoringLocalService() {

		return leadScoringLocalService;
	}

	/**
	 * Sets the lead scoring local service.
	 *
	 * @param leadScoringLocalService the lead scoring local service
	 */
	public void setLeadScoringLocalService(
		mx.movistar.col.lead.service.LeadScoringLocalService
			leadScoringLocalService) {

		this.leadScoringLocalService = leadScoringLocalService;
	}

	/**
	 * Returns the lead scoring persistence.
	 *
	 * @return the lead scoring persistence
	 */
	public LeadScoringPersistence getLeadScoringPersistence() {
		return leadScoringPersistence;
	}

	/**
	 * Sets the lead scoring persistence.
	 *
	 * @param leadScoringPersistence the lead scoring persistence
	 */
	public void setLeadScoringPersistence(
		LeadScoringPersistence leadScoringPersistence) {

		this.leadScoringPersistence = leadScoringPersistence;
	}

	/**
	 * Returns the nir local service.
	 *
	 * @return the nir local service
	 */
	public mx.movistar.col.lead.service.NirLocalService getNirLocalService() {
		return nirLocalService;
	}

	/**
	 * Sets the nir local service.
	 *
	 * @param nirLocalService the nir local service
	 */
	public void setNirLocalService(
		mx.movistar.col.lead.service.NirLocalService nirLocalService) {

		this.nirLocalService = nirLocalService;
	}

	/**
	 * Returns the nir remote service.
	 *
	 * @return the nir remote service
	 */
	public NirService getNirService() {
		return nirService;
	}

	/**
	 * Sets the nir remote service.
	 *
	 * @param nirService the nir remote service
	 */
	public void setNirService(NirService nirService) {
		this.nirService = nirService;
	}

	/**
	 * Returns the nir persistence.
	 *
	 * @return the nir persistence
	 */
	public NirPersistence getNirPersistence() {
		return nirPersistence;
	}

	/**
	 * Sets the nir persistence.
	 *
	 * @param nirPersistence the nir persistence
	 */
	public void setNirPersistence(NirPersistence nirPersistence) {
		this.nirPersistence = nirPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService
		getClassNameService() {

		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {

		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {

		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return NirService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Nir.class;
	}

	protected String getModelClassName() {
		return Nir.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = nirPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(
		type = mx.movistar.col.lead.service.BlackListLocalService.class
	)
	protected mx.movistar.col.lead.service.BlackListLocalService
		blackListLocalService;

	@BeanReference(type = mx.movistar.col.lead.service.BlackListService.class)
	protected mx.movistar.col.lead.service.BlackListService blackListService;

	@BeanReference(type = BlackListPersistence.class)
	protected BlackListPersistence blackListPersistence;

	@BeanReference(
		type = mx.movistar.col.lead.service.CallCenterLocalService.class
	)
	protected mx.movistar.col.lead.service.CallCenterLocalService
		callCenterLocalService;

	@BeanReference(type = mx.movistar.col.lead.service.CallCenterService.class)
	protected mx.movistar.col.lead.service.CallCenterService callCenterService;

	@BeanReference(type = CallCenterPersistence.class)
	protected CallCenterPersistence callCenterPersistence;

	@BeanReference(type = CallCenterFinder.class)
	protected CallCenterFinder callCenterFinder;

	@BeanReference(
		type = mx.movistar.col.lead.service.CampaignLocalService.class
	)
	protected mx.movistar.col.lead.service.CampaignLocalService
		campaignLocalService;

	@BeanReference(type = mx.movistar.col.lead.service.CampaignService.class)
	protected mx.movistar.col.lead.service.CampaignService campaignService;

	@BeanReference(type = CampaignPersistence.class)
	protected CampaignPersistence campaignPersistence;

	@BeanReference(type = mx.movistar.col.lead.service.LeadLocalService.class)
	protected mx.movistar.col.lead.service.LeadLocalService leadLocalService;

	@BeanReference(type = mx.movistar.col.lead.service.LeadService.class)
	protected mx.movistar.col.lead.service.LeadService leadService;

	@BeanReference(type = LeadPersistence.class)
	protected LeadPersistence leadPersistence;

	@BeanReference(type = LeadFinder.class)
	protected LeadFinder leadFinder;

	@BeanReference(
		type = mx.movistar.col.lead.service.LeadScoringLocalService.class
	)
	protected mx.movistar.col.lead.service.LeadScoringLocalService
		leadScoringLocalService;

	@BeanReference(type = LeadScoringPersistence.class)
	protected LeadScoringPersistence leadScoringPersistence;

	@BeanReference(type = mx.movistar.col.lead.service.NirLocalService.class)
	protected mx.movistar.col.lead.service.NirLocalService nirLocalService;

	@BeanReference(type = NirService.class)
	protected NirService nirService;

	@BeanReference(type = NirPersistence.class)
	protected NirPersistence nirPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserService.class
	)
	protected com.liferay.portal.kernel.service.UserService userService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

}