/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mx.movistar.col.lead.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

import mx.movistar.col.lead.model.Lead;
import mx.movistar.col.lead.model.LeadModel;
import mx.movistar.col.lead.model.LeadSoap;

/**
 * The base model implementation for the Lead service. Represents a row in the &quot;LEAD_Lead&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>LeadModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeadImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeadImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class LeadModelImpl extends BaseModelImpl<Lead> implements LeadModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lead model instance should use the <code>Lead</code> interface instead.
	 */
	public static final String TABLE_NAME = "LEAD_Lead";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"leadId", Types.BIGINT},
		{"campaignId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"dueDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"title", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"source", Types.VARCHAR}, {"type_", Types.VARCHAR},
		{"product", Types.VARCHAR}, {"hasEmail", Types.BOOLEAN},
		{"hasPhone", Types.BOOLEAN}, {"hasName", Types.BOOLEAN},
		{"extra1", Types.BOOLEAN}, {"extra2", Types.BOOLEAN},
		{"extra3", Types.BOOLEAN}, {"totalScoring", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leadId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("campaignId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dueDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("source", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("product", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hasEmail", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("hasPhone", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("hasName", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("extra1", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("extra2", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("extra3", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("totalScoring", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LEAD_Lead (uuid_ VARCHAR(75) null,leadId LONG not null primary key,campaignId LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,dueDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,title STRING null,description VARCHAR(75) null,source VARCHAR(75) null,type_ VARCHAR(75) null,product VARCHAR(75) null,hasEmail BOOLEAN,hasPhone BOOLEAN,hasName BOOLEAN,extra1 BOOLEAN,extra2 BOOLEAN,extra3 BOOLEAN,totalScoring INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table LEAD_Lead";

	public static final String ORDER_BY_JPQL = " ORDER BY lead.title ASC";

	public static final String ORDER_BY_SQL = " ORDER BY LEAD_Lead.title ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		mx.movistar.col.lead.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.mx.movistar.col.lead.model.Lead"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		mx.movistar.col.lead.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.mx.movistar.col.lead.model.Lead"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		mx.movistar.col.lead.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.mx.movistar.col.lead.model.Lead"),
		true);

	public static final long CAMPAIGNID_COLUMN_BITMASK = 1L;

	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long STATUS_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long TITLE_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Lead toModel(LeadSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Lead model = new LeadImpl();

		model.setUuid(soapModel.getUuid());
		model.setLeadId(soapModel.getLeadId());
		model.setCampaignId(soapModel.getCampaignId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDueDate(soapModel.getDueDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setTitle(soapModel.getTitle());
		model.setDescription(soapModel.getDescription());
		model.setSource(soapModel.getSource());
		model.setType(soapModel.getType());
		model.setProduct(soapModel.getProduct());
		model.setHasEmail(soapModel.isHasEmail());
		model.setHasPhone(soapModel.isHasPhone());
		model.setHasName(soapModel.isHasName());
		model.setExtra1(soapModel.isExtra1());
		model.setExtra2(soapModel.isExtra2());
		model.setExtra3(soapModel.isExtra3());
		model.setTotalScoring(soapModel.getTotalScoring());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Lead> toModels(LeadSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Lead> models = new ArrayList<Lead>(soapModels.length);

		for (LeadSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		mx.movistar.col.lead.service.util.ServiceProps.get(
			"lock.expiration.time.mx.movistar.col.lead.model.Lead"));

	public LeadModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leadId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeadId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leadId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Lead.class;
	}

	@Override
	public String getModelClassName() {
		return Lead.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Lead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Lead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Lead, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Lead)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Lead, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Lead, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Lead)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Lead, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Lead, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Lead>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Lead.class.getClassLoader(), Lead.class, ModelWrapper.class);

		try {
			Constructor<Lead> constructor =
				(Constructor<Lead>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Lead, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Lead, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Lead, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Lead, Object>>();
		Map<String, BiConsumer<Lead, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Lead, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object uuid) {
					lead.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"leadId",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getLeadId();
				}

			});
		attributeSetterBiConsumers.put(
			"leadId",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object leadId) {
					lead.setLeadId((Long)leadId);
				}

			});
		attributeGetterFunctions.put(
			"campaignId",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getCampaignId();
				}

			});
		attributeSetterBiConsumers.put(
			"campaignId",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object campaignId) {
					lead.setCampaignId((Long)campaignId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object groupId) {
					lead.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object companyId) {
					lead.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object userId) {
					lead.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object userName) {
					lead.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object createDate) {
					lead.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object modifiedDate) {
					lead.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"dueDate",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getDueDate();
				}

			});
		attributeSetterBiConsumers.put(
			"dueDate",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object dueDate) {
					lead.setDueDate((Date)dueDate);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object status) {
					lead.setStatus((Integer)status);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserId",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getStatusByUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserId",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object statusByUserId) {
					lead.setStatusByUserId((Long)statusByUserId);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserName",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getStatusByUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserName",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object statusByUserName) {
					lead.setStatusByUserName((String)statusByUserName);
				}

			});
		attributeGetterFunctions.put(
			"statusDate",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getStatusDate();
				}

			});
		attributeSetterBiConsumers.put(
			"statusDate",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object statusDate) {
					lead.setStatusDate((Date)statusDate);
				}

			});
		attributeGetterFunctions.put(
			"title",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getTitle();
				}

			});
		attributeSetterBiConsumers.put(
			"title",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object title) {
					lead.setTitle((String)title);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object description) {
					lead.setDescription((String)description);
				}

			});
		attributeGetterFunctions.put(
			"source",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getSource();
				}

			});
		attributeSetterBiConsumers.put(
			"source",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object source) {
					lead.setSource((String)source);
				}

			});
		attributeGetterFunctions.put(
			"type",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getType();
				}

			});
		attributeSetterBiConsumers.put(
			"type",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object type) {
					lead.setType((String)type);
				}

			});
		attributeGetterFunctions.put(
			"product",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getProduct();
				}

			});
		attributeSetterBiConsumers.put(
			"product",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object product) {
					lead.setProduct((String)product);
				}

			});
		attributeGetterFunctions.put(
			"hasEmail",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getHasEmail();
				}

			});
		attributeSetterBiConsumers.put(
			"hasEmail",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object hasEmail) {
					lead.setHasEmail((Boolean)hasEmail);
				}

			});
		attributeGetterFunctions.put(
			"hasPhone",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getHasPhone();
				}

			});
		attributeSetterBiConsumers.put(
			"hasPhone",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object hasPhone) {
					lead.setHasPhone((Boolean)hasPhone);
				}

			});
		attributeGetterFunctions.put(
			"hasName",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getHasName();
				}

			});
		attributeSetterBiConsumers.put(
			"hasName",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object hasName) {
					lead.setHasName((Boolean)hasName);
				}

			});
		attributeGetterFunctions.put(
			"extra1",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getExtra1();
				}

			});
		attributeSetterBiConsumers.put(
			"extra1",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object extra1) {
					lead.setExtra1((Boolean)extra1);
				}

			});
		attributeGetterFunctions.put(
			"extra2",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getExtra2();
				}

			});
		attributeSetterBiConsumers.put(
			"extra2",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object extra2) {
					lead.setExtra2((Boolean)extra2);
				}

			});
		attributeGetterFunctions.put(
			"extra3",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getExtra3();
				}

			});
		attributeSetterBiConsumers.put(
			"extra3",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object extra3) {
					lead.setExtra3((Boolean)extra3);
				}

			});
		attributeGetterFunctions.put(
			"totalScoring",
			new Function<Lead, Object>() {

				@Override
				public Object apply(Lead lead) {
					return lead.getTotalScoring();
				}

			});
		attributeSetterBiConsumers.put(
			"totalScoring",
			new BiConsumer<Lead, Object>() {

				@Override
				public void accept(Lead lead, Object totalScoring) {
					lead.setTotalScoring((Integer)totalScoring);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getLeadId() {
		return _leadId;
	}

	@Override
	public void setLeadId(long leadId) {
		_leadId = leadId;
	}

	@JSON
	@Override
	public long getCampaignId() {
		return _campaignId;
	}

	@Override
	public void setCampaignId(long campaignId) {
		_columnBitmask |= CAMPAIGNID_COLUMN_BITMASK;

		if (!_setOriginalCampaignId) {
			_setOriginalCampaignId = true;

			_originalCampaignId = _campaignId;
		}

		_campaignId = campaignId;
	}

	public long getOriginalCampaignId() {
		return _originalCampaignId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getDueDate() {
		return _dueDate;
	}

	@Override
	public void setDueDate(Date dueDate) {
		_dueDate = dueDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTitle(), languageId, useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		_columnBitmask = -1L;

		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(
				LocalizationUtil.updateLocalization(
					getTitle(), "Title", title, languageId, defaultLanguageId));
		}
		else {
			setTitle(
				LocalizationUtil.removeLocalization(
					getTitle(), "Title", languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitleMap(
		Map<Locale, String> titleMap, Locale defaultLocale) {

		if (titleMap == null) {
			return;
		}

		setTitle(
			LocalizationUtil.updateLocalization(
				titleMap, getTitle(), "Title",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getSource() {
		if (_source == null) {
			return "";
		}
		else {
			return _source;
		}
	}

	@Override
	public void setSource(String source) {
		_source = source;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@JSON
	@Override
	public String getProduct() {
		if (_product == null) {
			return "";
		}
		else {
			return _product;
		}
	}

	@Override
	public void setProduct(String product) {
		_product = product;
	}

	@JSON
	@Override
	public boolean getHasEmail() {
		return _hasEmail;
	}

	@JSON
	@Override
	public boolean isHasEmail() {
		return _hasEmail;
	}

	@Override
	public void setHasEmail(boolean hasEmail) {
		_hasEmail = hasEmail;
	}

	@JSON
	@Override
	public boolean getHasPhone() {
		return _hasPhone;
	}

	@JSON
	@Override
	public boolean isHasPhone() {
		return _hasPhone;
	}

	@Override
	public void setHasPhone(boolean hasPhone) {
		_hasPhone = hasPhone;
	}

	@JSON
	@Override
	public boolean getHasName() {
		return _hasName;
	}

	@JSON
	@Override
	public boolean isHasName() {
		return _hasName;
	}

	@Override
	public void setHasName(boolean hasName) {
		_hasName = hasName;
	}

	@JSON
	@Override
	public boolean getExtra1() {
		return _extra1;
	}

	@JSON
	@Override
	public boolean isExtra1() {
		return _extra1;
	}

	@Override
	public void setExtra1(boolean extra1) {
		_extra1 = extra1;
	}

	@JSON
	@Override
	public boolean getExtra2() {
		return _extra2;
	}

	@JSON
	@Override
	public boolean isExtra2() {
		return _extra2;
	}

	@Override
	public void setExtra2(boolean extra2) {
		_extra2 = extra2;
	}

	@JSON
	@Override
	public boolean getExtra3() {
		return _extra3;
	}

	@JSON
	@Override
	public boolean isExtra3() {
		return _extra3;
	}

	@Override
	public void setExtra3(boolean extra3) {
		_extra3 = extra3;
	}

	@JSON
	@Override
	public int getTotalScoring() {
		return _totalScoring;
	}

	@Override
	public void setTotalScoring(int totalScoring) {
		_totalScoring = totalScoring;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Lead.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Lead.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			Lead.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public Lead toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Lead>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeadImpl leadImpl = new LeadImpl();

		leadImpl.setUuid(getUuid());
		leadImpl.setLeadId(getLeadId());
		leadImpl.setCampaignId(getCampaignId());
		leadImpl.setGroupId(getGroupId());
		leadImpl.setCompanyId(getCompanyId());
		leadImpl.setUserId(getUserId());
		leadImpl.setUserName(getUserName());
		leadImpl.setCreateDate(getCreateDate());
		leadImpl.setModifiedDate(getModifiedDate());
		leadImpl.setDueDate(getDueDate());
		leadImpl.setStatus(getStatus());
		leadImpl.setStatusByUserId(getStatusByUserId());
		leadImpl.setStatusByUserName(getStatusByUserName());
		leadImpl.setStatusDate(getStatusDate());
		leadImpl.setTitle(getTitle());
		leadImpl.setDescription(getDescription());
		leadImpl.setSource(getSource());
		leadImpl.setType(getType());
		leadImpl.setProduct(getProduct());
		leadImpl.setHasEmail(isHasEmail());
		leadImpl.setHasPhone(isHasPhone());
		leadImpl.setHasName(isHasName());
		leadImpl.setExtra1(isExtra1());
		leadImpl.setExtra2(isExtra2());
		leadImpl.setExtra3(isExtra3());
		leadImpl.setTotalScoring(getTotalScoring());

		leadImpl.resetOriginalValues();

		return leadImpl;
	}

	@Override
	public int compareTo(Lead lead) {
		int value = 0;

		value = getTitle().compareTo(lead.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Lead)) {
			return false;
		}

		Lead lead = (Lead)obj;

		long primaryKey = lead.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LeadModelImpl leadModelImpl = this;

		leadModelImpl._originalUuid = leadModelImpl._uuid;

		leadModelImpl._originalCampaignId = leadModelImpl._campaignId;

		leadModelImpl._setOriginalCampaignId = false;

		leadModelImpl._originalGroupId = leadModelImpl._groupId;

		leadModelImpl._setOriginalGroupId = false;

		leadModelImpl._originalCompanyId = leadModelImpl._companyId;

		leadModelImpl._setOriginalCompanyId = false;

		leadModelImpl._setModifiedDate = false;

		leadModelImpl._originalStatus = leadModelImpl._status;

		leadModelImpl._setOriginalStatus = false;

		leadModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Lead> toCacheModel() {
		LeadCacheModel leadCacheModel = new LeadCacheModel();

		leadCacheModel.uuid = getUuid();

		String uuid = leadCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			leadCacheModel.uuid = null;
		}

		leadCacheModel.leadId = getLeadId();

		leadCacheModel.campaignId = getCampaignId();

		leadCacheModel.groupId = getGroupId();

		leadCacheModel.companyId = getCompanyId();

		leadCacheModel.userId = getUserId();

		leadCacheModel.userName = getUserName();

		String userName = leadCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			leadCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			leadCacheModel.createDate = createDate.getTime();
		}
		else {
			leadCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leadCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leadCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date dueDate = getDueDate();

		if (dueDate != null) {
			leadCacheModel.dueDate = dueDate.getTime();
		}
		else {
			leadCacheModel.dueDate = Long.MIN_VALUE;
		}

		leadCacheModel.status = getStatus();

		leadCacheModel.statusByUserId = getStatusByUserId();

		leadCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = leadCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			leadCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			leadCacheModel.statusDate = statusDate.getTime();
		}
		else {
			leadCacheModel.statusDate = Long.MIN_VALUE;
		}

		leadCacheModel.title = getTitle();

		String title = leadCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			leadCacheModel.title = null;
		}

		leadCacheModel.description = getDescription();

		String description = leadCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			leadCacheModel.description = null;
		}

		leadCacheModel.source = getSource();

		String source = leadCacheModel.source;

		if ((source != null) && (source.length() == 0)) {
			leadCacheModel.source = null;
		}

		leadCacheModel.type = getType();

		String type = leadCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			leadCacheModel.type = null;
		}

		leadCacheModel.product = getProduct();

		String product = leadCacheModel.product;

		if ((product != null) && (product.length() == 0)) {
			leadCacheModel.product = null;
		}

		leadCacheModel.hasEmail = isHasEmail();

		leadCacheModel.hasPhone = isHasPhone();

		leadCacheModel.hasName = isHasName();

		leadCacheModel.extra1 = isExtra1();

		leadCacheModel.extra2 = isExtra2();

		leadCacheModel.extra3 = isExtra3();

		leadCacheModel.totalScoring = getTotalScoring();

		return leadCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Lead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Lead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Lead, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Lead)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Lead, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Lead, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Lead, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Lead)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Lead>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _leadId;
	private long _campaignId;
	private long _originalCampaignId;
	private boolean _setOriginalCampaignId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _dueDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _description;
	private String _source;
	private String _type;
	private String _product;
	private boolean _hasEmail;
	private boolean _hasPhone;
	private boolean _hasName;
	private boolean _extra1;
	private boolean _extra2;
	private boolean _extra3;
	private int _totalScoring;
	private long _columnBitmask;
	private Lead _escapedModel;

}