/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mx.movistar.col.lead.model.impl;

import aQute.bnd.annotation.ProviderType;

import mx.movistar.col.lead.model.Lead;
import mx.movistar.col.lead.service.LeadLocalServiceUtil;

/**
 * The extended model base implementation for the Lead service. Represents a row in the &quot;LEAD_Lead&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeadImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeadImpl
 * @see Lead
 * @generated
 */
@ProviderType
public abstract class LeadBaseImpl extends LeadModelImpl implements Lead {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lead model instance should use the <code>Lead</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LeadLocalServiceUtil.addLead(this);
		}
		else {
			LeadLocalServiceUtil.updateLead(this);
		}
	}

}